### ISSUE TITLE
한자키 관련 빈창이 뜨는 문제.

### ISSUE THREAD

**Issue by nemonein** [dasom-im/dasom-qt#3]
안녕하세요.
https://github.com/dasom-im/dasom-qt/issues/2 에서 말씀드린 한자키 관련 문제입니다.

hanja-keys 에 (아마도) 코드에서 인식되지 않는 키가 설정되어 있을 경우, 한국어 입력 상태에서 한자키를 누르거나 마우스 클릭을 할 경우 빈 창이 뜹니다.

예를 들어,

> org.freedesktop.Dasom.engines.jeongeum.hanja-keys : ['hangul-hanja', 'F12']

이렇게 설정을 해놓은 경우, 한국어 입력 상태에서 아무 것도 입력하지 않은 뒤 '한자'키를 누르거나, 마우스로 클릭을 했을 경우 아래 그림처럼 빈 한자창이 뜹니다.

![smp](https://cloud.githubusercontent.com/assets/5688288/11841520/3ad355d4-a441-11e5-921e-c4b6a01b315f.png)
![bomi](https://cloud.githubusercontent.com/assets/5688288/11841523/3dd678ce-a441-11e5-95aa-97a5c20ecb9b.png)
![tea](https://cloud.githubusercontent.com/assets/5688288/11841524/3e000db0-a441-11e5-8ca8-21f65248130f.png)

이 중, Tea 와 Smplayer 는 한자키/마우스 클릭 어느 것이나 빈 창을 보여주었고,
보미는 한자키로만 빈창이 나타났습니다.
Gtk 쪽에선 이런 문제가 발생하지 않았습니다.

더불어, 한자키 설정시 f12 는 '펑션키 F12'로 인식하지만, 대문자 F12 는 인식하지 않습니다.

확인부탁드립니다.

**Comment by cogniti** [comment]
원인을 찾았습니다. 이렇게 테스트 코드를 넣어서 확인해보았습니다.
```diff
hodong@hodong-VirtualBox:~/dasom-qt$ git diff
diff --git a/qt5/im-dasom-qt5.cpp b/qt5/im-dasom-qt5.cpp
index 5b6def4..a433bfa 100644
--- a/qt5/im-dasom-qt5.cpp
+++ b/qt5/im-dasom-qt5.cpp
@@ -242,8 +242,19 @@ DasomInputContext::filterEvent (const QEvent *event)
 {
   g_debug (G_STRLOC ": %s", G_STRFUNC);
 
+  bool is_accepted = false;
+/*
   if (G_UNLIKELY (!inputMethodAccepted()))
     return false;
+*/
+
+  is_accepted = inputMethodAccepted();
+
+  if (is_accepted == true)
+    g_debug ("inputMethodAccepted() == true");
+  else
+    g_debug ("inputMethodAccepted() == false");
+
 
   gboolean         retval;
   const QKeyEvent *key_event = static_cast<const QKeyEvent *>( event );
```
shift + space 로 한/영 전환할 때 키 누를 때 `true`, 키 뗄 때 `true` 가 나옵니다.
그러나 Alt 키로 한/영 전환할 때 키 누를 때 `false`, 키 뗄 때 `true` 가 나옵니다.

**Comment by ghost** [comment]
> 더불어, 한자키 설정시 f12 는 '펑션키 F12'로 인식하지만, 대문자 F12 는 인식하지 않습니다.

이 점은 맞게 작동하는 것입니다.

`F12` 넣고 마우스 클릭했을 때, 한자창 뜨는 것은 다솜 버그 같습니다.

**Comment by ghost** [comment]
마우스 클릭시 한자창 뜨는 문제는 곧 해결됩니다. 그러나,
아무 것도 입력하지 않은 상태에서 한자키 누를 경우 빈 한자창이 뜨는데 이것은 의도된 것입니다.
그리고 `뮬` 을 입력한 후 한자키를 누를 경우 빈 한자창이 뜨는데 찾은 한자가 없어서 그렇습니다.
이 동작도 의도된 것입니다. 이 부분은 지금 현재는 고칠 생각이 없습니다. 미래에는 어떻게 될 지 모르겠습니다.

우리는 이러한 한자창을 생각해 볼 수 있습니다.
한자키를 눌렀을 때 한자창이 뜨는데 한자창 윗 부분에 입력칸이 있고 그 입력칸에 한글을 입력하면 한자 목록이 나오는 것을 생각해 볼 수 있습니다. 이렇게 구현하겠다는 얘기가 아니라 기존 한자창과는 다르면서 더 나은 한자창도 있을 수 있다는 의미입니다.

한자창 동작은 dasom-pinyin 을 설계하면서 다시 살펴볼 기회가 있습니다.
한자창은 후보창(candidate window) 라는 물건인데, 이 물건은 중국어나 일본어를 입력할 때에도 공통적으로 사용할 물건입니다.
한자창에 대한 좋은 의견이 있으시면 https://github.com/dasom-im/dasom/issues 를 작성해 주세요.

감사합니다.
