### ISSUE TITLE
kate에서 vi 모드를 사용하면 정상적으로 입력이 안 됩니다.

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom-qt#4]
https://github.com/dasom-im/dasom/issues/43#issuecomment-165728707 에 보고된 내용입니다.

kate에서 vi 모드를 사용하면 정상적으로 입력이 안 됩니다.

**Comment by ghost** [comment]
@igxactly
이는 kate 또는 Qt 버그입니다. 입력기에서 그 버그를 피해가려면 dasom-qt 코드가 지저분해지고 완전하게 해결되지도 않습니다.

**Comment by ghost** [comment]
``` diff
hodong@hodong-VirtualBox:~/dasom-qt$ git diff
diff --git a/qt5/im-dasom-qt5.cpp b/qt5/im-dasom-qt5.cpp
index 218a862..ebde3fa 100644
--- a/qt5/im-dasom-qt5.cpp
+++ b/qt5/im-dasom-qt5.cpp
@@ -245,6 +245,12 @@ DasomInputContext::filterEvent (const QEvent *event)
   if (G_UNLIKELY (!qApp->focusObject() || !inputMethodAccepted()))
     return false;

+  QObject *input = qApp->focusObject();
+  QInputMethodQueryEvent queryEvent(Qt::ImEnabled);
+  QCoreApplication::sendEvent(input, &queryEvent);
+  if (!queryEvent.value(Qt::ImEnabled).toBool())
+    return false;
+
   gboolean         retval;
   const QKeyEvent *key_event = static_cast<const QKeyEvent *>( event );
   DasomEvent      *dasom_event;
```

이런 테스트 코드를 넣어도 kate vi mode 가 정상 작동하지 않습니다.
kate 에서 vi mode 에서 `ESC` 눌렀을 때 `Qt::ImEnabled` 플래그를 해제해야 할 것 같습니다. 아울러 `inputMethodAccepted()` 했을 때 `false` 값이 나와야 합니다.
kate 측에 버그 리포트를 하는 것이 좋겠습니다.

**Comment by igxactly** [comment]
그렇군요. 한 번 알아봐야겠네요.

**Comment by ghost** [comment]
회피 코드를 적용하였습니다.

https://github.com/dasom-im/dasom-jeongeum/commit/0eb6e0f6a06526253c4b9a13a0112c7ad3a72bf4
https://github.com/dasom-im/dasom-jeongeum/commit/ec12b979f1de4a560d23afb9c3f6d5018935f099

어플 버그를 회피하는 코드(workaround code)를 dasom 에 넣는 이유는 어플을 당장 사용해야 하는데  어플 버그가 고쳐지고 릴리즈되어 배포판에 탑재되기까지 시간이 걸리기 때문입니다.

입력기에서 어플 버그를 회피할 수 있는 방법은 극히 제한되어 있기 때문에 ibus, fcitx, uim, dasom 등의 입력기에서 어플 버그를 근본적으로 해결하는 것은 불가능합니다.

따라서 어플 버그에 대한 근본적인 해결은 해당 어플 프로젝트에서 다루어져야 합니다.

다솜 프로젝트, 다솜 팀원 및 다솜 개발자는 응용 어플리케이션에 대한 보증 책임이 없습니다. 또한 다솜 입력기에 대한 보증 책임이 없습니다.

감사합니다.
